import { jsPDF } from "jspdf";

export const downloadReport = (username, report) => {
  const doc = new jsPDF();

  const PAGE_WIDTH = 210;
  const MARGIN = 20;

  // =========================
  // HEADER
  // =========================
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, PAGE_WIDTH, 24, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);

  doc.text("DevScout AI Report", 20, 15);

  doc.setTextColor(0, 0, 0);

  let y = 35;

  // =========================
  // CANDIDATE
  // =========================
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Candidate", MARGIN, y);

  y += 6;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(username, MARGIN, y);

  y += 12;

  // =========================
  // TECHNICAL ASSESSMENT
  // =========================
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Technical Assessment", MARGIN, y);

  y += 7;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const scores = [
    `Overall Score : ${report.overallScore}`,
    `Backend Score : ${report.backendScore}`,
    `Frontend Score : ${report.frontendScore}`,
    `Database Score : ${report.databaseScore}`,
    `AI Score : ${report.aiScore}`,
  ];

  scores.forEach((item) => {
    doc.text(item, MARGIN, y);
    y += 5;
  });

  y += 5;

  // =========================
  // TECHNOLOGIES
  // =========================
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Technologies", MARGIN, y);

  y += 7;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const techText = Object.keys(report.technologies).join(", ");

  const techLines = doc.splitTextToSize(
    techText,
    170
  );

  doc.text(
    techLines,
    MARGIN,
    y
  );

  y += techLines.length * 5 + 5;

  // =========================
  // AI SUMMARY
  // =========================
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("AI Recruiter Summary", MARGIN, y);

  y += 7;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const summaryLines = doc.splitTextToSize(
    report.aiAnalysis,
    170
  );

  const pageHeight =
    doc.internal.pageSize.height;

  summaryLines.forEach((line) => {
    if (y > pageHeight - 15) {
      doc.addPage();
      y = 20;
    }

    doc.text(line, MARGIN, y);
    y += 4.5;
  });

  // =========================
  // FOOTER
  // =========================
  doc.setDrawColor(220);
  doc.line(
    20,
    pageHeight - 15,
    190,
    pageHeight - 15
  );

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    "Generated by DevScout AI",
    20,
    pageHeight - 8
  );

  doc.save(`${username}_report.pdf`);
};