import AIInsights from "../AIInsights";

function InsightsSection({ analysis }) {
  return (
    <div className="section-stack">
      <section className="panel insights-panel insights-panel--ai">
        <div className="panel-header">
          <div>
            <h3 className="panel-title">AI insights</h3>
            <p className="panel-subtitle">Qualitative interpretation · not a verified score · generated by Gemini</p>
          </div>
          <span className="ai-badge">AI generated</span>
        </div>
        <AIInsights analysis={analysis} />
      </section>
    </div>
  );
}

export default InsightsSection;